# Generated by Django 3.1.3 on 2023-02-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230220_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='dateofservice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='suitabletime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
