# Generated by Django 3.1.3 on 2023-02-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230220_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='actype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
