# Generated by Django 3.1.3 on 2023-02-20 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230220_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinghistory',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.technician'),
        ),
    ]
