# Generated by Django 3.1.3 on 2023-02-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_trackinghistory_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinghistory',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
