# Generated by Django 3.1.3 on 2023-02-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20230221_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinghistory',
            name='othercharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackinghistory',
            name='partcharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackinghistory',
            name='servicecharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
