# Generated by Django 3.1.3 on 2023-02-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20230222_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinghistory',
            name='status1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
