# Generated by Django 3.1.3 on 2023-02-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_trackinghistory_status1'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinghistory',
            name='remark1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
