# Generated by Django 3.1.3 on 2023-02-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_trackinghistory_remark1'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinghistory',
            name='status2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
