# Generated by Django 3.1.3 on 2023-03-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_trackinghistory_status2'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinghistory',
            name='remark2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackinghistory',
            name='status3',
            field=models.CharField(blank=True, default='Waiting for confirmation', max_length=100, null=True),
        ),
    ]
