# Generated by Django 3.1.3 on 2023-03-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20230327_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status3',
            field=models.CharField(blank=True, default='Waiting for confirmation', max_length=100, null=True),
        ),
    ]
