# Generated by Django 3.1.3 on 2023-03-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_request_status3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status3',
            field=models.CharField(blank=True, default='Waiting for Confirmation', max_length=100, null=True),
        ),
    ]
