# Generated by Django 3.1.3 on 2023-03-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20230327_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinghistory',
            name='status3',
            field=models.CharField(blank=True, default='Waiting for Confirmation', max_length=100, null=True),
        ),
    ]
