# Generated by Django 3.1.3 on 2023-03-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20230327_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reasonforcancel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
