# Generated by Django 3.1.3 on 2023-03-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20230327_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='fromdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='todate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
