# Generated by Django 3.1.3 on 2023-03-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20230330_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='totalprice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
