# Generated by Django 3.1.3 on 2023-04-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_request_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='fromdate',
        ),
        migrations.RemoveField(
            model_name='request',
            name='status3',
        ),
        migrations.RemoveField(
            model_name='request',
            name='todate',
        ),
        migrations.RemoveField(
            model_name='trackinghistory',
            name='status3',
        ),
    ]
