# Generated by Django 4.0.2 on 2023-04-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20230401_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancel',
            name='reasonforcancel',
            field=models.CharField(blank=True, default='Not Updated Yet', max_length=100, null=True),
        ),
    ]
