# Generated by Django 4.0.2 on 2023-04-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_cancel_reasonforcancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancel',
            name='reasonforcancel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
